/**
 * dz dialect sentence API
 * Sentences API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkSentenceDto } from './bulk-sentence-dto';


export interface BulkCreateSentenceDto { 
    sentenceList: Array<BulkSentenceDto>;
}

