/**
 * dz dialect sentence API
 * Sentences API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkSentenceWordPropositionDto } from './bulk-sentence-word-proposition-dto';
import { BulkSentenceAdditionalInformationDto } from './bulk-sentence-additional-information-dto';


export interface BulkSentenceDto { 
    dz: string;
    dz_ar: string;
    fr: string;
    word_propositions: BulkSentenceWordPropositionDto;
    additionnal_information: BulkSentenceAdditionalInformationDto;
}

