/**
 * dz dialect sentence API
 * Sentences API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulkSentenceAdditionalInformationDto { 
    pronouns?: Array<string>;
    adjectives?: Array<string>;
    verbs?: Array<string>;
    tense?: string;
    schema?: string;
}

