/**
 * DZDialect API
 * DZDialect API v1.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContributionSentenceDTO { 
    id?: string;
    dz?: string;
    dz_ar?: string;
    fr?: string;
    author_id?: string;
    thumb_up_count?: number;
    thumb_down_count?: number;
}

