/**
 * DZDialect API
 * DZDialect API v1.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Translation } from './translation';


export interface ContributionSentence { 
    translations?: Array<Translation>;
    id?: string;
    category?: string;
    thumb_up_count?: number;
    thumb_down_count?: number;
    author_id?: string;
}

