/**
 * dz dialect sentence API
 * Sentences API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSentenceDto { 
    dz: string;
    dz_ar: string;
    fr: string;
    word_propositions_dz: Array<string>;
    word_propositions_fr: Array<string>;
    pronouns: Array<string>;
    adjectives: Array<string>;
    verbs: Array<string>;
    tense: string;
    schema: string;
}

