/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SentenceContentDTO } from './sentence-content-dto';
import { WordPropositionsDTO } from './word-propositions-dto';


export interface SentenceDTO { 
    dz?: string;
    dz_ar?: string;
    fr?: string;
    additionnal_information?: SentenceContentDTO;
    word_propositions?: WordPropositionsDTO;
}

