/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SentenceContentDTO { 
    verb?: string;
    adverb?: string;
    question?: string;
    adjective?: string;
    noun?: string;
    tense?: string;
    schema?: string;
    pronoun?: string;
}

