/**
 * DZDialect API
 * DZDialect API v1.0
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Translation { 
    lang?: Translation.LangEnum;
    value?: string;
    gender?: Translation.GenderEnum;
    ar_value?: string;
}
export namespace Translation {
    export type LangEnum = 'FR' | 'DZ';
    export const LangEnum = {
        FR: 'FR' as LangEnum,
        DZ: 'DZ' as LangEnum
    };
    export type GenderEnum = 'M' | 'F' | 'X';
    export const GenderEnum = {
        M: 'M' as GenderEnum,
        F: 'F' as GenderEnum,
        X: 'X' as GenderEnum
    };
}


