/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WordPropositionsDTO { 
    dz?: Array<string>;
    dz_ar?: Array<string>;
    fr?: Array<string>;
}

