/**
 * DzDialect Identity API
 * DzDialect Identity API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProvidersEnum = 'basic' | 'twitter';

export const ProvidersEnum = {
    BASIC: 'basic' as ProvidersEnum,
    TWITTER: 'twitter' as ProvidersEnum
};

