/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChapterResponseDto { 
    id: string;
    name: string;
    description: string;
    isPresentation: boolean;
    createdAt: string;
    updatedAt: string;
}

