/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTrainingExamQuestionDto } from './create-training-exam-question-dto';


export interface CreateTrainingExamDto { 
    name: string;
    questions: Array<CreateTrainingExamQuestionDto>;
}

