/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTrainingExamQuestionResponseDto } from './create-training-exam-question-response-dto';


export interface CreateTrainingExamResponseDto { 
    id: string;
    name: string;
    questions: Array<CreateTrainingExamQuestionResponseDto>;
}

