/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTrainingExamResponseDto } from './create-training-exam-response-dto';


export interface CreateTrainingCourseResponseDto { 
    id: string;
    name: string;
    description: string;
    exams: Array<CreateTrainingExamResponseDto>;
}

