/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ExamCopyStateEnum = 'COMPLETED' | 'IN_PROGRESS' | 'SKIPPED';

export const ExamCopyStateEnum = {
    COMPLETED: 'COMPLETED' as ExamCopyStateEnum,
    IN_PROGRESS: 'IN_PROGRESS' as ExamCopyStateEnum,
    SKIPPED: 'SKIPPED' as ExamCopyStateEnum
};

