/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetExamQuestionResponseDto } from './get-exam-question-response-dto';
import { ExamCopyStateEnum } from './exam-copy-state-enum';


export interface GetExamCopyResponseDto { 
    id: string;
    examId: string;
    state: ExamCopyStateEnum;
    questions: Array<GetExamQuestionResponseDto>;
    currentQuestionIndex: number;
    createdAt: string;
    updatedAt: string;
}

