/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetExamListTrainingCourseExamResponseDto } from './get-exam-list-training-course-exam-response-dto';


export interface GetExerciseResponseDto { 
    id: string;
    name: string;
    description: string;
    trainingId: boolean;
    exams: Array<GetExamListTrainingCourseExamResponseDto>;
    order: number;
    createdAt: string;
    updatedAt: string;
}

