/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionTypeEnum } from './question-type-enum';


export interface GetExamQuestionResponseDto { 
    id: string;
    type: QuestionTypeEnum;
    question: string;
    order: number;
    propositions: Array<string>;
}

