/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetExamListTrainingCourseExamQuestionResponseDto } from './get-exam-list-training-course-exam-question-response-dto';


export interface GetExamListTrainingCourseExamResponseDto { 
    id: string;
    name: string;
    courseId: string;
    questions: Array<GetExamListTrainingCourseExamQuestionResponseDto>;
    order: number;
    createdAt: string;
    updatedAt: string;
}

