/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetExamResponseDto } from './get-exam-response-dto';


export interface GetTrainingResponseDto { 
    id: string;
    exam: GetExamResponseDto;
}

