/**
 * DzDialect Training API
 * DzDialect Training API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type QuestionTypeEnum = 'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'WORD_LIST';

export const QuestionTypeEnum = {
    SINGLE_CHOICE: 'SINGLE_CHOICE' as QuestionTypeEnum,
    MULTIPLE_CHOICE: 'MULTIPLE_CHOICE' as QuestionTypeEnum,
    WORD_LIST: 'WORD_LIST' as QuestionTypeEnum
};

